version: "3.9"
services:
  certbot:
    container_name: certbot_moodle
    hostname: certbot
    image: certbot/certbot:v2.1.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      moodle_local:
  reverse:
    container_name: proxy_moodle
    hostname: reverse
    image: nginx:1.23.2-alpine
    networks:
      moodle_local:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
      - ./includes/:/etc/nginx/includes/:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
networks:
  moodle_local:
    name: moodle_network_local
    external: true
